version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Wave #2"
description: "Seeker #1 is a visual experience about blind walkers with dice. They throw it on move based on score to reach a remote destination"
url: "http://behrooz-tahanzadeh.github.io/seeker-1/"
date: "Oct 2014"
googleAnalyticsCode: "UA-40560087-5"
